global using Budget.Application.Abstractions;
global using Budget.Application.Expenses;
global using Budget.Application.Expenses.GetAll;
global using Budget.Domain.Expenses;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Security.Claims;
